# Generated by Django 4.2.2 on 2023-06-30 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCategoria', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuentostr', models.CharField(max_length=50, null=True)),
                ('descuento', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUser', models.AutoField(db_column='idUser', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('telefono', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombresubcategoria', models.CharField(max_length=50, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50, null=True)),
                ('precio', models.IntegerField(default=0, null=True)),
                ('imgProducto', models.ImageField(null=True, upload_to='imgproductos')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.categoria')),
                ('descuento', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.descuento')),
                ('subcategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50, null=True)),
                ('ciudad', models.CharField(max_length=50, null=True)),
                ('país', models.CharField(max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
