# Generated by Django 4.2.1 on 2023-07-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_delete_usuario_perfil_apellido_materno_perfil_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
