# Generated by Django 4.1.2 on 2023-06-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venta', '0002_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUser', models.AutoField(db_column='idUser', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('telefono', models.CharField(max_length=45)),
            ],
        ),
    ]
